### PR TITLE
Fixing self._sample typo in sound_level #53

### PR DESCRIPTION
**Pull request by kevinjwalters**
Correcting typo, `self._sample` -> `self._samples` in `sound_level`.

### CODE REVIEW

**Comment by dhalbert** [comment]
Thanks for noticing this. The word "sample" is really overloaded in the code, and I am doing a cleanup. I will push a new commit after testing.

**Comment by dhalbert** [comment]
@kevinjwalters See what you think of this. I tested `play_tone()` and `sound_level` on a CLUE.

**Comment by kevinjwalters** [comment]
@dhalbert LGTM.

It does raise the question about harmonsiation with other libraries. I suppose this isn't that important though as it's clearly not part of an interface.

I glanced at one other board to see how it's handled and the _**same minor error**_ is present there. Perhaps it's worth a wider rummage? https://github.com/adafruit/Adafruit_CircuitPython_CircuitPlayground/blob/511f55ca17a742a5249540d92fa97e66a4226887/adafruit_circuitplayground/bluefruit.py#L90-L91

**Comment by dhalbert** [comment]
We can and should fix that too!

**Pull request merged**
